#!/bin/bash

    # 2018.9.5
    echo "2018.9.5 compare with GraphChi" >> graphchi_metrics.txt.statistics 

# ## LiveJournal   
#     echo "app = PageRank, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 20, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/pagerank
#     done

#     echo "app = RandomWalkDomination, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 6, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/rwdomination
#     done

#     echo "app = Graphlet, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 10000, L = 4, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/graphlet
#     done

#     echo "app = PersonalizedPageRank, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 10, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/personalizedpagerank
#     done

#     echo "app = SimRank, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 2000, L = 11, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/simrank
#     done

#     echo "app = Reachability, dataset = LiveJournal from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 100, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/reachability
#     done

# ## Wikipedia
#     echo "app = PageRank, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 20, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/pagerank file "../DataSet/Wikipedia/wikipedia_sorted.data" N 12150977
#     done

#     echo "app = RandomWalkDomination, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 6, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/rwdomination file "../DataSet/Wikipedia/wikipedia_sorted.data" N 12150977
#     done

#     echo "app = Graphlet, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 10000, L = 4, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/graphlet file "../DataSet/Wikipedia/wikipedia_sorted.data" N 12150977
#     done

#     echo "app = PersonalizedPageRank, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 10, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/personalizedpagerank file "../DataSet/Wikipedia/wikipedia_sorted.data"  N 12150977 source 1source 1
#     done

    echo "app = SimRank, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
    echo "R = 2000, L = 11, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
    for(( times = 0; times < 5; times++))
    do
        echo "times = " $times " from echo"
        ./bin/apps/simrank file "../DataSet/Wikipedia/wikipedia_sorted.data" N 12150977 a 1 b 3
    done

#     echo "app = Reachability, dataset = Wikipedia from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 100, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/reachability file "../DataSet/Wikipedia/wikipedia_sorted.data" N 12150977 a 1 b 3
#     done

# # Twitter
#     echo "app = PageRank, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 20, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/pagerank file "../DataSet/Twitter/twitter_rv.net" N 61578415 
#     done

#     echo "app = RandomWalkDomination, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 6, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/rwdomination file "../DataSet/Twitter/twitter_rv.net" N 61578415 
#     done

#     echo "app = Graphlet, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 10000, L = 4, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/graphlet file "../DataSet/Twitter/twitter_rv.net" N 61578415 
#     done

#     echo "app = PersonalizedPageRank, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 10, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/personalizedpagerank file "../DataSet/Twitter/twitter_rv.net" N 61578415 source 12
#     done

#     echo "app = SimRank, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 2000, L = 11, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/simrank file "../DataSet/Twitter/twitter_rv.net" N 61578415 a 12 b 13
#     done

#     echo "app = Reachability, dataset = Twitter from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 100, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/reachability file "../DataSet/Twitter/twitter_rv.net" N 61578415  a 12 b 13
#     done

# # Friendster
#     echo "dataset = Friendster ...." >> graphchi_metrics.txt.statistics 
#     echo "app = PageRank, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 20, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/pagerank file "../DataSet/Friendster/out.friendster-reorder" N 68349467 
#     done

#     echo "app = RandomWalkDomination, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1×N, L = 6, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/rwdomination file "../DataSet/Friendster/out.friendster-reorder" N 68349467 
#     done

#     echo "app = Graphlet, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 10000, L = 4, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/graphlet file "../DataSet/Friendster/out.friendster-reorder" N 68349467 
#     done

#     echo "app = PersonalizedPageRank, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 10, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/personalizedpagerank file "../DataSet/Friendster/out.friendster-reorder" N 68349467 source 12
#     done

#     echo "app = SimRank, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 2000, L = 11, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/simrank file "../DataSet/Friendster/out.friendster-reorder" N 68349467  a 12 b 13
#     done

#     echo "app = Reachability, dataset = Friendster from echo" >> graphchi_metrics.txt.statistics 
#     echo "R = 1000, L = 100, choose prob=0.2 from echo" >> graphchi_metrics.txt.statistics 
#     for(( times = 0; times < 5; times++))
#     do
#         echo "times = " $times " from echo"
#         ./bin/apps/reachability file "../DataSet/Friendster/out.friendster-reorder" N 68349467  a 12 b 13
#     done
